for MYSUB in 9004_EP-12126 9006_EO-12389 9008_JO-12613 9009_CRB-12609
do
applywarp -w /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/fmri/rs_reg.feat/reg/standard2highres_warp.nii.gz -i /Users/erin/Desktop/Projects/MRGFUS/scripts/rois_standardspace/juelich_prob_WM_Callosal_body_R --postmat=/Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/xfms/str2diff.mat -o /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/juelich_prob_WM_Callosal_body_R --interp=nn -r /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/nodif_brain.nii.gz

applywarp -w /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/fmri/rs_reg.feat/reg/standard2highres_warp.nii.gz -i /Users/erin/Desktop/Projects/MRGFUS/scripts/rois_standardspace/mni_prob_Cerebellum_thr10_R --postmat=/Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/xfms/str2diff.mat -o /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/mni_prob_Cerebellum_thr10_R --interp=nn -r /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/nodif_brain.nii.gz

applywarp -w /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/fmri/rs_reg.feat/reg/standard2highres_warp.nii.gz -i /Users/erin/Desktop/Projects/MRGFUS/scripts/rois_standardspace/mni_prob_Cerebellum_thr10_L --postmat=/Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/xfms/str2diff.mat -o /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/mni_prob_Cerebellum_thr10_L --interp=nn -r /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/nodif_brain.nii.gz

fslmaths /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/juelich_prob_WM_Callosal_body_R.nii.gz -add /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/mni_prob_Cerebellum_thr10_L -bin /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/exclude_L_cerebellum_R_callosal_body

mkdir -p /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion.bedpostX/T1_lesion_mask_filled_waypoint_R_cerebellum_exclude_R_corpus_callosum_L_cerebellum
/usr/local/fsl/bin/probtrackx2  -x /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/T1_lesion_mask_filled.nii.gz  -l --onewaycondition -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/exclude_L_cerebellum_R_callosal_body.nii.gz --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion.bedpostX/nodif_brain_mask  --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion.bedpostX/T1_lesion_mask_filled_waypoint_R_cerebellum_exclude_R_corpus_callosum_L_cerebellum --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/${MYSUB}/diffusion/rois/mni_prob_Cerebellum_thr10_R --waycond=AND
done