/usr/local/fsl/bin/probtrackx2 -x /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil -l --onewaycondition --wayorder -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/nodif_brain_mask --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_exclude2_corticalwaypoint --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_exclude2_corticalwaypoint/waypoints.txt --waycond=AND --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/exclude_L2

/usr/local/fsl/bin/probtrackx2 -x /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil -l --onewaycondition --wayorder -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/nodif_brain_mask --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_thalterm --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_thalterm/waypoints.txt --waycond=AND --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/exclude_L2 --wtstop=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/thalamus_R 

/usr/local/fsl/bin/probtrackx2 -x /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil -l --onewaycondition --wayorder -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/nodif_brain_mask --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_thalwaypoint --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_thalwaypoint/waypoints.txt --waycond=AND --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/exclude_L2 

/usr/local/fsl/bin/probtrackx2 -x /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_R_dil -l --onewaycondition --wayorder -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/nodif_brain_mask --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_R_dil_exclude2_corticalwaypoint --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_R_dil_exclude2_corticalwaypoint/waypoints.txt --waycond=AND --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/exclude_R2 

/usr/local/fsl/bin/probtrackx2 -x /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil -l --onewaycondition --wayorder -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/nodif_brain_mask --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_thalterm --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_L_dil_thalterm/waypoints.txt --waycond=AND --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/exclude_L2 --wtstop=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/thalamus_R 

/usr/local/fsl/bin/probtrackx2 -x /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_R_dil -l --onewaycondition --wayorder -c 0.2 -S 2000 --steplength=0.5 -P 5000 --fibthresh=0.01 --distthresh=0.0 --sampvox=0.0 --forcedir --opd -s /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/merged -m /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion.bedpostX/nodif_brain_mask --dir=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_R_dil_thalwaypoint --waypoints=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/dentate_R_dil_thalwaypoint/waypoints.txt --waycond=AND --avoid=/Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/diffusion/Kwon_ROIs/exclude_R2 

