analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9001_SH 11692 /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11692/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11692/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11692/diffusion/xfms/T1_2_diff_bbr.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9001_SH-11692/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9001_SH 11644 /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11692/fmri/rs_reg.feat/reg/ /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11644/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH_longitudinal_xfms/mT1_day1_2_diff_pre_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9001_SH-11692/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9001_SH 12271 /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-11692/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH-12271/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9001_SH_longitudinal_xfms/mT1_day1_2_diff_3M_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9001_SH-11692/anat/T1_lesion_mask_filled


analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9002_RA 11833 /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-11833/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-11833/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-11833/diffusion/xfms/T1_2_diff_bbr.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9002_RA-11833/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9002_RA 11764 /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-11833/fmri/rs_reg.feat/reg/ /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-11764/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA_longitudinal_xfms/mT1_day1_2_diff_pre_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9002_RA-11833/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9002_RA 12388 /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-11833/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA-12388/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9002_RA_longitudinal_xfms/mT1_day1_2_diff_3M_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9002_RA-11833/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9004_EP 12203 /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12203/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12203/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12203/diffusion/xfms/T1_2_diff_bbr.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9004_EP-12203/anat/T1_lesion_mask_filled

#looks as though thresholded tract includes callosal fibres that just end before midsag
analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9004_EP 12126 /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12203/fmri/rs_reg.feat/reg/ /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12126/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP_longitudinal_xfms/mT1_day1_2_diff_pre_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9004_EP-12203/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9004_EP 12955 /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12203/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP-12955/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9004_EP_longitudinal_xfms/mT1_day1_2_diff_3M_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9004_EP-12203/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9006_EO 12487 /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-12487/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-12487/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-12487/diffusion/xfms/T1_2_diff_bbr.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9006_EO-12487/anat/T1_lesion_mask_filled

#suprathresholded fibres passing through PC
analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9006_EO 12389 /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-12487/fmri/rs_reg.feat/reg/ /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-12389/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO_longitudinal_xfms/mT1_day1_2_diff_pre_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9006_EO-12487/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9006_EO 13017 /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-12487/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO-13017/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9006_EO_longitudinal_xfms/mT1_day1_2_diff_3M_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9006_EO-12487/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9007_RB 12910 /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-12910/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-12910/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-12910/diffusion/xfms/T1_2_diff_bbr.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_L_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9007_RB-12910/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9007_RB 12461 /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-12910/fmri/rs_reg.feat/reg/ /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-12461/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB_longitudinal_xfms/mT1_day1_2_diff_pre_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_L_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9007_RB-12910/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9007_RB 13055 /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-12910/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB-13055/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9007_RB_longitudinal_xfms/mT1_day1_2_diff_3M_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_L_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9007_RB-12910/anat/T1_lesion_mask_filled

#does not track to cerebellum
analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9009_CRB 13043 /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-13043/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-13043/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-13043/diffusion/xfms/T1_2_diff_bbr.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9009_CRB-13043/anat/T1_lesion_mask_filled

analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9009_CRB 12609 /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-13043/fmri/rs_reg.feat/reg/ /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-12609/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB_longitudinal_xfms/mT1_day1_2_diff_pre_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9009_CRB-13043/anat/T1_lesion_mask_filled

#just barely tracks to cerebellum
analysis_tract_from_contralateral_lesion_Apr24_2018_input.sh 9009_CRB 13623 /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-13043/fmri/rs_reg.feat/reg /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB-13623/fmri/rs_reg.feat/reg/standard2highres_warp /Users/erin/Desktop/Projects/MRGFUS/analysis/9009_CRB_longitudinal_xfms/mT1_day1_2_diff_3M_bbr_6dof.mat /Users/erin/Desktop/Projects/MRGFUS/scripts/harvardoxford-subcortical/thalamus_R_final /Users/erin/Desktop/Projects/MRGFUS/analysis_lesion_masks/9009_CRB-13043/anat/T1_lesion_mask_filled